# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that configures the environment for this solution accelerator

# trigger:
#   branches:
#     include:
#     - v2-preview
#   paths:
#     include:
#     - Custom_Script/mlops-pipelines/1-setup/*
#     - Custom_Script/mlops-pipelines/scripts/download_data.py
#     - Custom_Script/mlops-pipelines/scripts/register_dataset.py

variables:
- template: ../many-models-variables.yml
- group: manymodels-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy_infra
  displayName: 'Deploy Infra'
  jobs:
  - template: deploy-infra/deploy-infra.template.yml
    parameters:
      environment: '$(ENVIRONMENT)'
      serviceConnection: '$(SERVICECONNECTION_GROUP)'
      resourceGroup: '$(RESOURCE_GROUP)'
      resourcesLocation: '$(LOCATION)'
      storageAccountName: '$(STORAGEACCOUNT_NAME)'
      keyVaultName: '$(KEYVAULT_NAME)'
      appInsightsName: '$(APPINSIGHTS_NAME)'
      containerRegistryName: '$(CONTAINERREGISTRY_NAME)'
      amlWorkspaceName: '$(AMLWORKSPACE_NAME)'

- stage: environment_setup
  displayName: 'Environment Setup'
  jobs:
  - template: environment-setup/environment-setup.template.yml
    parameters:
      sdkVersion: '$(SDK_VERSION)'
      serviceConnection: '$(SERVICECONNECTION_GROUP)'
      resourceGroup: '$(RESOURCE_GROUP)'
      resourcesLocation: '$(LOCATION)'
      amlWorkspaceName: '$(AMLWORKSPACE_NAME)'
      amlComputeName: '$(AML_COMPUTE_NAME)'
      aksName: '$(AKS_NAME)'
      aksResourceGroup: '$(AKS_RESOURCE_GROUP)'
      amlAksName: '$(AML_AKS_NAME)'
      amlTrainDatasetName: '$(AML_DATASET_NAME)_train'
      amlInferenceDatasetName: '$(AML_DATASET_NAME)_inference'
      maxFiles: '$(DATASET_MAXFILES)'
